// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChainInfo struct {
	Id                    int64  `json:"id"`                      // 自增主键
	ChainId               string `json:"chain_id"`                // 链ID（字符串存储，兼容16进制和10进制）
	ChainIdDecimal        int64  `json:"chain_id_decimal"`        // 链ID（10进制数字，用于排序和比较）
	Name                  string `json:"name"`                    // 区块链网络全称
	ShortName             string `json:"short_name"`              // 链简称（用于内部标识）
	Slug                  string `json:"slug"`                    // URL友好的标识符
	ChainType             string `json:"chain_type"`              // 链类型
	Environment           string `json:"environment"`             // 网络环境
	IsActive              bool   `json:"is_active"`               // 是否启用
	RpcUrls               string `json:"rpc_urls"`                // RPC URL列表（JSON数组）
	WssUrls               string `json:"wss_urls"`                // WebSocket URL列表（JSON数组）
	DefaultRpcIndex       int64  `json:"default_rpc_index"`       // 默认RPC索引
	ExplorerUrl           string `json:"explorer_url"`            // 区块浏览器URL
	ApiUrl                string `json:"api_url"`                 // 区块浏览器API URL
	NativeCurrency        string `json:"native_currency"`         // 原生代币信息
	IconUrl               string `json:"icon_url"`                // 图标URL
	Color                 string `json:"color"`                   // 主题颜色（16进制颜色码）
	IsTestnet             bool   `json:"is_testnet"`              // 是否是测试网
	CurrencySymbol        string `json:"currency_symbol"`         // 货币符号（显示用）
	BlockExplorerName     string `json:"block_explorer_name"`     // 区块浏览器名称
	DisplayOrder          int64  `json:"display_order"`           // 显示排序
	IsDeprecated          bool   `json:"is_deprecated"`           // 是否已弃用
	SupportsEip1559       bool   `json:"supports_eip1559"`        // 是否支持EIP-1559
	SupportsBatchRequests bool   `json:"supports_batch_requests"` // 是否支持批量请求
	CreatedAt             string `json:"created_at"`              // 创建时间
	UpdatedAt             string `json:"updated_at"`              // 更新时间
}

type PingPangRequest struct {
	Pang string `path:"pang,options=ping|pang"`
}

type PingPangResponse struct {
	Message   string `json:"message"`
	Timestamp int64  `json:"timestamp"`
}

type SystemTimeResponse struct {
	Message        string `json:"message"`
	Timestamp      string `json:"timestamp"`
	TimeUnix       int64  `json:"timeUnix"`
	TimeUnixNano   int64  `json:"timeUnixNano"`
	Timezone       string `json:"timezone"`
	TimezoneOffset int64  `json:"timezoneOffset"`
	DaylightSaving int64  `json:"daylightSaving"`
}
