// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"mt_node/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 系统API group
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/system/ping/:pang",
				Handler: PingPangHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/time",
				Handler: SystemTimeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
